Repository gig-central/gig-repo-1, pull requests merged in 2020-06, with the labels that each got.

#303 Update welcome_page.php
  application/views/welcome_page.php
Labels: enhancement

#316 Controllers/gig.php has new enhancement to pagination
  application/controllers/Gig.php
  ersMartin FreiwaldDesktopGithubgig-central-dummyCUsersMartin FreiwaldDesktopGithubgig-central-dummy[A[A[A[A[B[B[B
Labels: Needed, Should, enhancement

#317 fixed layout of recent gigs and map
  public/css/custom_styles.css
  public/css/custom_styles_index.css
Labels: enhancement

#325 Added sign up page
  application/libraries/Navigation.php
  application/views/admins/login.php
  application/views/profiles/add.php
Labels: Must

#329 updated add.php responsiveness
  application/views/profiles/add.php
Labels: bug
